-- 코드를 작성해주세요
select ID, FISH_NAME, LENGTH
from FISH_INFO A
left join FISH_NAME_INFO B
on A.FISH_TYPE = B.FISH_TYPE
where LENGTH IN (
    SELECT MAX(LENGTH)
    FROM FISH_INFO C
    WHERE C.FISH_TYPE = A.FISH_TYPE
    GROUP BY FISH_TYPE
)
AND LENGTH is NOT NULL
ORDER BY A.ID ASC;
